#!/usr/bin/env bash
#clear
#export PS4='\033[90m+${LINENO} in ${#BASH_SOURCE[@]}>${FUNCNAME[0]}:${BASH_SOURCE[@]##*/} \033[0m'
#set -x

#echo "starting: $0 <LOG_LEVEL=$1>"

### new.method

pm-tools.ts.init() {
  local path="$1"
  shift

  if [ -z "$path" ]; then
    this.absolutePath .
    path=$RESULT
  fi

  this.absolutePath $path
  path=$RESULT

  cd $path

  if [ -f "$path/package.json" ]; then
    npm i typescript --save-dev
    npx tsc --init                  # create a tsconfig.json
    mkdir src
    mkdir dist
    mkdir out
    mkdir test
    {
      echo ""
      echo "#ts gen folder" >>.gitignore
      echo "out" 
    } >>.gitignore
  else
    warn.log "please run first
    
    npm init
    
    "
  fi


}

pm-tools.colordiff() {
  diff --color=always      \
      "$1" "$2" 
}

pm-tools.diff.full.color() {
  diff --old-group-format=$'\e[0;31m%<\e[0m'      \
      --new-group-format=$'\e[0;32m%>\e[0m'       \
      --unchanged-group-format=$'\e[0;90m%<\e[0m' \
      "$1" "$2" 
}

pm-tools.diff.extend() {
  {
  echo "{
  \"extends\": \"./tsconfig.json\","
  diff --new-group-format=$'%<'      \
      --old-group-format=$''       \
      --unchanged-group-format=$'' \
      "$1" "$2" 
  echo ""
  echo "}"
  } >"$2".extends.json
  cat "$2".extends.json
}


pm-tools.diff.side.by.side() {
  diff -y \
      "$1" "$2" 
  echo  "
  $1                              $2" 
}

pm-tools.create.all.extend.configs() {
    pm-tools.diff.extend ../../tsconfig.json ../../tsconfig.cjs.json
    pm-tools.diff.extend ../../tsconfig.json ../../tsconfig.es6.umd.json
    pm-tools.diff.extend ../../tsconfig.json ../../tsconfig.esm.json
    pm-tools.diff.extend ../../tsconfig.json ../../tsconfig.esnext.esnext.json
}


pm-tools.usage()
{
  local this=${0##*/}
  echo "You started: "
  echo "$0

  Usage:
  $this: command   description and Parameter

      usage     prints this dialog while it will print the status when there are no parameters          
      v         print version information
      init      initializes ...nothing yet
      ----      --------------------------
  
  Examples
    $this v
    $this init
  "
}

pm-tools.start()
{
  #echo "sourcing init"
  source this

  # if [ -z "$1" ]; then
  #   status.discover "$@"
  #   return 0
  # fi

  this.start "$@"
}

pm-tools.start "$@"

